services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  node_app_pratica_github_actions:
    container_name: node_app_pratica_github_actions
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
