name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      -name: Check out repository code
      uses: actions/checkout@v3
      -name: Make a new envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_POSTGRES_USER: "postgres"
        envkey_POSTGRES_PASSWORD: "postgres"
        envkey_POSTGRES_DB: "postgres"
        envkey_DATABASE_URL: "postgresql://postgres:postgres@db-test:5432/students__tests"
        file_name: .env.test
      -name: Run tests
      run: docker-compose -f docker-compose-tests.yml run node_app_pratica_github_actions-test npm run test 

