name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.PG_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.PG_PW}}
          envkey_POSTGRES_DB: ${{secrets.PG_DB}}
          envkey_DATABASE_URL: ${{secrets.DB_URL}}
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_pratica_githun_actions-test npm run test
